#!/bin/bash

#
# Run fstrim on given mountpoints when the system is idle, as defined by:
# - We're on AC power
# - Both 1-minute and 5-minute load average are below the configured threshold
#
# Run this in a cronjob on SSDs, daily or so.
#

MAX_LOAD_AVG="0.03"
MOUNTPOINTS="$@"
SLEEPTIME="2m"

system_idle() {
	on_ac_power || return 1

	local load_avg=( $(</proc/loadavg) )
	local cpu_idle=$(echo "${load_avg[0]} < $MAX_LOAD_AVG && ${load_avg[1]} < $MAX_LOAD_AVG" | bc -l)
	[[ $cpu_idle == 1 ]]
	return $?
}

usage() {
	echo Usage:
	echo "$(basename $0) MOUNTPOINT..."
	echo
	echo Example:
	echo "$(basename $0) / /home /boot"
}

if [[ -z $1 ]]; then
	usage
	exit 1
fi
for mp in $@; do
	dev=`mount | grep $mp | cut -d ' ' -f 1`
	if ! blockdev --getsize64 $dev &> /dev/null; then
		usage
		exit 1
	fi
done

sleep 1m

on_ac_power || SLEEPTIME="9m"
while ! system_idle; do
	sleep $SLEEPTIME
done

touch /var/run/fstrimd
for mp in $MOUNTPOINTS; do
	ionice -c Idle fstrim $mp
done
